app/source/Schedule/Schedule/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "suhedeleapp"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('suhedeleapp/', include('suhedeleapp.urls')),
]

app/source/Schedule/suhedeleapp/urls.py
from django.urls import path
from .views import testView, signupView, formView, createView, loginView

app_name = 'suhedeleapp'
urlpatterns = [
    path("test/", testView, name='test'),
    path("signup/", signupView, name='signup'),
    path("form/", formView, name='form'),
    path("create/", createView, name='create'),
    path("login/", loginView, name='login'),
]

app/source/Schedule/suhedeleapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Userlist(models.Model):
    name = models.CharField('名前',  max_length=20)
    password = models.CharField('パスワード', max_length=50)

    def __str__(self):
        return '<id:' + str(self.name) + ',' + self.password + '>'

class Todolist(models.Model):
    day = models.DateField('日付け', default= timezone.now)
    content = models.CharField('予定', max_length=50)
    

    def __str__(self):
        return '<id:' + str(self.id) + ',' + self.content + '>'

app/source/Schedule/suhedeleapp/forms.py
from django import forms
from .models import Todolist, Userlist

class TodoAdd(forms.ModelForm):
    class Meta:
        model = Todolist
        fields = ['day','content']
        
        widgets = {
            'day': forms.NumberInput(attrs={
                "type": "date"
            })
        }


class UserAdd(forms.ModelForm):
    class Meta:
        model = Userlist
        fields = ['name','password']

app/source/Schedule/suhedeleapp/views.py
from django.shortcuts import render, redirect
from .models import Todolist   , Userlist
from .forms import TodoAdd, UserAdd
from django.contrib import messages

# Create your views here.

def testView(request):
	return render(request, "suhedeleapp/test.html")

# def signupView(request):
# 	plate = {
# 		'aaa' : "今日は"
# 	}

# 	return render(request, "suhedeleapp/signup.html", plate)

def formView(request):
	todo = Todolist.objects.all().order_by('day')
	todo_2 = Todolist.objects.values()
	user = Userlist.objects.values()
	my_dict = {
        'title':'予定',
        'user': user,
        'val2': todo,
    }
	return render(request, 'suhedeleapp/form.html', my_dict)


def createView(request):
	message = ''  # 初期表示ではカラ
	if (request.method == 'POST'):
		form = TodoAdd(request.POST)
		if form.is_valid():
			form.save()
			return redirect('suhedeleapp:form')
		else:
			message = '再入力して下さい'
	modelform_dict = {
        'title':'予定登録',
        'form': TodoAdd(),
		'message': message,  # エラーメッセージ
    }
	return render(request, 'suhedeleapp/create.html', modelform_dict)


def signupView(request):
	message = ''  # 初期表示ではカラ
	# print(request.method)
	if (request.method == 'POST'):
		form = UserAdd(request.POST)
		# name = request.POST["name"]
		# password = request.POST["password"]
		# print(name)
		if form.is_valid():
			form.save()
			return redirect('suhedeleapp:login')
		else:
			message = '再入力して下さい'

	else: #初回アクセス時…空のフォームがほしいとき
		form = UserAdd()

	modelform_dict2 = {
        'title':'新規登録',
        'form': UserAdd(),
		'message': message,  # エラーメッセージ
    }
	return render(request, 'suhedeleapp/signup.html', modelform_dict2)



def loginView(request):
    print('request.method == POST')
    print(request.method)

    log = False  # 変数 log を初期化
    
    if request.method == 'POST':
        next = request.POST.get('next')
        form = UserAdd(request.POST)
        if form.is_valid():
            print('成功')

            name = request.POST["name"]
            password = request.POST["password"]
            # print(name)
            # print(password)

            info = Userlist.objects.all()
            for user in info:
                # print(f'ID: {user.id}, name: {user.name}, password: {user.password}')
                if (name == user.name and password == user.password):
                    # print('正しいです。')
                    log = True

            if log:
				# ログイン成功メッセージを設定
                messages.success(request, '')
                return redirect('suhedeleapp:form')
            else:
				# ログインエラーメッセージを設定
                messages.error(request, 'ログインに失敗しました。正しい情報を入力してください。')
                return redirect('suhedeleapp:login')

        else:
            print('そんな値はないです')

    else:  # 初回アクセス時…空のフォームがほしいとき
        form = UserAdd()

    return render(request, 'suhedeleapp/login.html', {'form': form})

app/source/Schedule/suhedeleapp/templates/suhedeleapp/create.html
{% load static %}

<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <title>{{ title }}</title>
</head>
<body>
  <h1>{{ title }}</h1>
  <a href="{% url 'suhedeleapp:form' %}">予定画面へ</a>
  <br>
  <table>
    <form action="{% url 'suhedeleapp:create' %}" method="post">
      {% csrf_token %}
      <!-- {{ form.as_table }} -->
      {{ form.day }}
      <br>
      {{ form.content }}
      <tr>
        <td></td>
        <td><input type="submit" value="登録"></td>
      </tr>
    </form>
  </table>
</body>
</html>

app/source/Schedule/suhedeleapp/templates/suhedeleapp/form.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
  <title>{{ title }}</title>
</head>
<body>
  <h1>{{ title }}</h1>
  <form action="{% url 'suhedeleapp:create' %}" method="post"></form>
  <a href="{% url 'suhedeleapp:create' %}">予定登録</a>
  <table>
    {% for i2 in val2 %}
    <tr>
      <!-- <td>{{ i2.id }}</td> -->
      <td>{{ i2.day }}</td>
      <td>{{ i2.content }}</td>
    </tr>
    {% endfor %}
  </table>

<!-- 
  <table>
    {% for u in user %}
    <tr>
      <td>{{ u.name }}</td>
      <td>{{ u.password }}</td>
    </tr>
    {% endfor %}
  </table> -->
  <a href="{% url 'suhedeleapp:login' %}">ログアウト</a>
  <!-- <button onclick="location.href='suhedeleapp:create'">予定登録</button> -->

</form>
</body>
</html>

app/source/Schedule/suhedeleapp/templates/suhedeleapp/login.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>login</title>
</head>

<body>
    <div class="pt-4">
        <h1 class="login-name">ログイン</h1>
        <form action="{% url 'suhedeleapp:login' %}" method="POST">
            {% csrf_token %}
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <p><input type="hidden" name="next" value="{{next}}"></p>
            <!--{{ form.as_p }}-->
            <p>UserName</p>
            {{ form.name }}
            <p>Password</p>
            {{form.password}}
            <p class="botton"><input type="submit" value="LOGIN" class="login-botton"></p>
        </form>
        <p class="sinki"><a href="{% url 'suhedeleapp:signup' %}">新規登録はこちら</a></p>
        {{ form.management_form }}

        <!-- <a href="{% url 'suhedeleapp:form' %}">アプリへ</a> -->

    </div>
</body>

</html>

app/source/Schedule/suhedeleapp/templates/suhedeleapp/signup.html
{% load static %}

<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <title>{{ title }}</title>
</head>
<body>
  <h1>{{ title }}</h1>
  <table>
    <form action="{% url 'suhedeleapp:signup' %}" method="post">
      {% csrf_token %}
      <!-- {{ form.as_table }} -->
      <p>UserName</p>
      {{ form.name }}
      <br>
      <p>Password</p>
      {{ form.password }}
      <tr>
        <td></td>
        <td><input type="submit" value="送信"></td>
      </tr>
    </form>
  </table>
  <p class="log"><a href="{% url 'suhedeleapp:login' %}">ログインへ</a></p>
</body>
</html>

app/source/Schedule/suhedeleapp/templates/suhedeleapp/test.html
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>スケジュールアプリ</title>
  </head>
  <body>
    <h1>スケジュールアプリだよ！！！</h1>
  </body>
</html>